### ISSUE TITLE
YAML files not formatted when created

### ISSUE THREAD

**Issue by niyaznigmatullin** [JetBrains/educational-plugin#35]
The plugin seems to create YAML files with no indentation for list items. For instance on adding a task, `task-info.yaml` looks like this:

```
type: edu
files:
- name: src/Task.kt
  visible: true
- name: test/Tests.kt
  visible: false
```

After IDEA's `Reformat Code`, it becomes:

```
type: edu
files:
  - name: src/Task.kt
    visible: true
  - name: test/Tests.kt
    visible: false
```

Probably, would be better to create files according to what IDEA thinks is pretty formatted YAML file, to have consistent formats, because users usually call `Reformat Code` when manually editing the files.
